// @ts-nocheck
// Dataset estruturado para o Relatorio de Expansao para Vila Nova de Gaia.
// Todos os numeros sao snapshots de fontes publicas datadas — actualizar
// aqui quando houver release nova do Observatorio Imobiliario de Gaia,
// Confidencial Imobiliario ou INE.
//
// Estimativas por freguesia: triangulacao entre Idealista (relatorios
// publicos), Casa SAPO/SuperCasa (listagens activas), Observatorio de Gaia
// e Confidencial Imobiliario. Ranges em vez de pontos unicos para reflectir
// a dispersao real do stock.

export const DADOS_EXPANSAO_GAIA = {
  meta: {
    titulo: 'Relatorio de Expansao — Vila Nova de Gaia',
    subtitulo: 'Guia Orientador para Wholesaling 2026',
    autor: 'Alexandre Mendes, CFO Somnium Properties',
    data_captura_default: '2026-05-26',
    ticket_min: 100000,
    ticket_max: 200000,
  },

  macro: {
    populacao_2021: 303824,
    area_km2: 168.46,
    densidade: 1803,
    n_freguesias: 15,
    preco_medio_eur_m2: 2607,
    preco_medio_fonte: 'Confidencial Imobiliario (via Observatorio Imobiliario de Gaia)',
    preco_medio_data: '2025',
    preco_idealista_eur_m2: 2817,
    preco_idealista_yoy_pct: 5.2,
    preco_idealista_data: '2026-01',
    preco_byf_eur_m2: 2930,
    preco_byf_yoy_pct: -2.3,
    preco_byf_data: '2026-05',
    preco_novo_eur_m2: 3735,
    preco_existente_eur_m2: 1963,
    mediana_venda_eur: 337000,
    mediana_renda_eur: 1250,
    yield_bruto_pct: 4.74,
    renda_eur_m2: 13,
    licenciamentos_2024: 3400,
    aprovados_2024: 1900,
    licenciamentos_2025: 4170,
    aprovados_2025: 2910,
    licenciamentos_por_1000_hab: 6.6,
    licenciamentos_porto_grande: 3.7,
    licenciamentos_nacional: 3.3,
  },

  scoring: {
    pesos: {
      preco_entrada: 35,
      procura_liquidez: 25,
      servicos_amenidades: 15,
      potencial_revalorizacao: 15,
      concorrencia: 10,
    },
    escala: 'Cada eixo pontuado de 0 a 10. Score global = soma ponderada / 10 (escala final 0-10).',
    classificacao_regras: {
      recomendar: 'Score >= 7.5',
      monitorizar: 'Score 6.0 a 7.4',
      evitar: 'Score < 6.0',
    },
  },

  // 15 freguesias com scoring detalhado. Ordenadas por score (desc).
  freguesias: [
    {
      nome: 'Mafamude e Vilar do Paraiso',
      tipologia: 'Urbana centro',
      populacao: 52844,
      area_km2: 10.58,
      preco_eur_m2: 2300,
      preco_range: '2 000 - 2 800',
      var_yoy_pct: 5.0,
      tempo_venda_dias: 60,
      ticket_tipico_t2: '140 000 - 200 000',
      score: 8.8,
      criterios: { preco_entrada: 8, procura_liquidez: 10, servicos_amenidades: 10, potencial_revalorizacao: 9, concorrencia: 6 },
      classificacao: 'recomendar',
      perfil: 'Coracao administrativo de Gaia. Concentra Santo Ovidio, El Corte Ingles, Camara, hospitais e comercio. Stock heterogeneo (predios anos 70-90 com necessidade de reabilitacao). Procura permanente por proximidade ao metro Linha Amarela e futura Linha Rubi (Santo Ovidio + Soares dos Reis + Devesas).',
      drivers: ['Metro Santo Ovidio (Linha Amarela)', 'Linha Rubi: 4 estacoes na freguesia', 'Hospital da Luz Arrabida', 'Hospital Santos Silva', 'El Corte Ingles', 'Arrabida Shopping', 'Eixo VL8 / A1'],
      target_imovel: 'T2/T3 anos 70-90 para reabilitacao em predios com elevador. T1 perto do metro para arrendamento estudante/jovem profissional. Predios pequenos para sub-divisao.',
    },
    {
      nome: 'Oliveira do Douro',
      tipologia: 'Periurbana norte',
      populacao: 22615,
      area_km2: 7.54,
      preco_eur_m2: 1900,
      preco_range: '1 600 - 2 300',
      var_yoy_pct: 6.0,
      tempo_venda_dias: 75,
      ticket_tipico_t2: '110 000 - 175 000',
      score: 8.5,
      criterios: { preco_entrada: 10, procura_liquidez: 9, servicos_amenidades: 8, potencial_revalorizacao: 9, concorrencia: 7 },
      classificacao: 'recomendar',
      perfil: 'Encosta norte do Douro, vista para o Porto. Mistura stock antigo (predios anos 60-80) com nova construcao premium em pontos isolados. Yield medio 6-7% em arrendamento. Procura crescente de jovens famílias e expatriados que querem proximidade ao Porto sem premium da Ribeira.',
      drivers: ['VL9 (acesso A1)', 'Ponte do Freixo', 'Vista directa Douro/Porto', 'Continuidade urbana com Santa Marinha', 'Pipeline de reabilitacao em curso', 'Proximidade futura Linha Rubi'],
      target_imovel: 'T2/T3 em predios anos 70 sem elevador (preco entrada baixo, margem reabilitacao alta). Andares com vista Douro para premium em revenda.',
    },
    {
      nome: 'Vilar de Andorinho',
      tipologia: 'Periurbana',
      populacao: 18003,
      area_km2: 7.07,
      preco_eur_m2: 1850,
      preco_range: '1 500 - 2 200',
      var_yoy_pct: 5.0,
      tempo_venda_dias: 85,
      ticket_tipico_t2: '105 000 - 165 000',
      score: 8.3,
      criterios: { preco_entrada: 10, procura_liquidez: 8, servicos_amenidades: 7, potencial_revalorizacao: 9, concorrencia: 8 },
      classificacao: 'recomendar',
      perfil: 'Freguesia residencial calma, com forte presenca de familias de classe media. Stock dominado por T2/T3 anos 80-90 em predios de 4-6 andares. Preco entrada dos mais baixos de Gaia para zonas com transportes razoaveis e escolas. Concorrencia wholesale baixa.',
      drivers: ['Acesso A1/A20', 'Vila d Este (futuro PMO Linha Rubi)', 'Escolas E.B. 2,3 e secundarias', 'Proximidade Santo Ovidio', 'Reabilitacao do parque habitacional'],
      target_imovel: 'T2/T3 em predios anos 80-90 com necessidade de obra ligeira (cozinha, casa de banho, pintura). Andares baixos preferidos por familias.',
    },
    {
      nome: 'Avintes',
      tipologia: 'Periurbana sul',
      populacao: 10836,
      area_km2: 8.82,
      preco_eur_m2: 1750,
      preco_range: '1 400 - 2 100',
      var_yoy_pct: 4.5,
      tempo_venda_dias: 95,
      ticket_tipico_t2: '100 000 - 160 000',
      score: 8.0,
      criterios: { preco_entrada: 10, procura_liquidez: 7, servicos_amenidades: 7, potencial_revalorizacao: 8, concorrencia: 9 },
      classificacao: 'recomendar',
      perfil: 'Antiga vila industrial e piscatoria na margem do Douro. Charme historico (centro tradicional, festas locais) com preco abaixo da media. Procura sobretudo por familias locais. Concorrencia wholesale praticamente nula.',
      drivers: ['Marginal do Douro', 'Centro historico de Avintes', 'Ponte do Carro (acesso Porto)', 'Aforamento turistico crescente', 'Pipeline de reabilitacao publica'],
      target_imovel: 'T2 anos 70-90 com necessidade reabilitacao. Casas terreas antigas para deep value (reabilitacao integral). Predios pequenos no centro com potencial de divisao.',
    },
    {
      nome: 'Pedroso e Seixezelo',
      tipologia: 'Periurbana sul',
      populacao: 20226,
      area_km2: 20.88,
      preco_eur_m2: 1700,
      preco_range: '1 400 - 2 000',
      var_yoy_pct: 4.0,
      tempo_venda_dias: 90,
      ticket_tipico_t2: '100 000 - 150 000',
      score: 7.8,
      criterios: { preco_entrada: 10, procura_liquidez: 7, servicos_amenidades: 6, potencial_revalorizacao: 8, concorrencia: 9 },
      classificacao: 'recomendar',
      perfil: 'Freguesia extensa e mista (urbana junto a A1 e rural a leste). Stock barato em Pedroso urbano (zona Vacariça, Boavista). Industria activa que sustenta procura local. Crescimento de familias de classe media a procurar moradias.',
      drivers: ['Nó A1 Carvalhos', 'Industria activa', 'Acesso rapido ao Porto e Aveiro', 'Pipeline Cemusa/IKEA proximo', 'Crescimento residencial moradia'],
      target_imovel: 'T2/T3 em predios anos 80-2000 nas zonas urbanas. Moradias geminadas para revenda a familias locais. Predios pequenos no centro de Pedroso.',
    },
    {
      nome: 'Grijo e Sermonde',
      tipologia: 'Periurbana sul',
      populacao: 12018,
      area_km2: 12.99,
      preco_eur_m2: 1650,
      preco_range: '1 300 - 2 000',
      var_yoy_pct: 3.5,
      tempo_venda_dias: 110,
      ticket_tipico_t2: '95 000 - 145 000',
      score: 7.2,
      criterios: { preco_entrada: 10, procura_liquidez: 6, servicos_amenidades: 6, potencial_revalorizacao: 7, concorrencia: 9 },
      classificacao: 'monitorizar',
      perfil: 'Zona de transicao entre Gaia urbana e o concelho de Espinho. Bom acesso A1 e proximidade industrial. Stock mais barato mas tempo de venda mais longo. Atrai familias que pretendem moradia com terreno acessivel.',
      drivers: ['Nó A1 Carvalhos/Souto', 'Industria activa', 'Pipeline residencial em curso', 'Proximidade EFTA Portugal'],
      target_imovel: 'T2 anos 90 para arrendamento operario. Moradias pequenas para revenda. Predios isolados.',
    },
    {
      nome: 'Canelas',
      tipologia: 'Periurbana sul',
      populacao: 13918,
      area_km2: 6.90,
      preco_eur_m2: 1700,
      preco_range: '1 400 - 2 050',
      var_yoy_pct: 3.5,
      tempo_venda_dias: 100,
      ticket_tipico_t2: '95 000 - 150 000',
      score: 7.0,
      criterios: { preco_entrada: 9, procura_liquidez: 7, servicos_amenidades: 6, potencial_revalorizacao: 7, concorrencia: 8 },
      classificacao: 'monitorizar',
      perfil: 'Freguesia residencial estavel, ligada a Vilar de Andorinho. Stock T2/T3 anos 80-90 dominante. Procura razoavel de familias locais. Servicos basicos satisfatorios.',
      drivers: ['Acesso A20/A1', 'Escola Secundaria Ines de Castro', 'Proximidade Sao Felix/Coimbroes'],
      target_imovel: 'T2/T3 em predios anos 80 com necessidade de obra ligeira.',
    },
    {
      nome: 'Serzedo e Perosinho',
      tipologia: 'Periurbana sul',
      populacao: 13745,
      area_km2: 11.97,
      preco_eur_m2: 1600,
      preco_range: '1 300 - 1 950',
      var_yoy_pct: 3.0,
      tempo_venda_dias: 115,
      ticket_tipico_t2: '90 000 - 140 000',
      score: 6.8,
      criterios: { preco_entrada: 10, procura_liquidez: 5, servicos_amenidades: 5, potencial_revalorizacao: 7, concorrencia: 9 },
      classificacao: 'monitorizar',
      perfil: 'Zona mista urbana/rural a sul. Preco entrada baixo mas liquidez fraca. Procura sustentada por industria local e familias locais. Risco de tempo de venda elevado.',
      drivers: ['Acesso A1 Carvalhos', 'Centro de saude', 'Industria local'],
      target_imovel: 'Moradias pequenas para revenda. T2 em predios anos 80 nas zonas urbanas.',
    },
    {
      nome: 'Madalena',
      tipologia: 'Costeira',
      populacao: 10551,
      area_km2: 4.69,
      preco_eur_m2: 2800,
      preco_range: '2 200 - 3 500',
      var_yoy_pct: 4.0,
      tempo_venda_dias: 65,
      ticket_tipico_t2: '170 000 - 245 000',
      score: 6.5,
      criterios: { preco_entrada: 6, procura_liquidez: 9, servicos_amenidades: 7, potencial_revalorizacao: 7, concorrencia: 4 },
      classificacao: 'monitorizar',
      perfil: 'Praia da Madalena e zona costeira muito procurada para AL e segunda habitacao. Preco acima do target mas existe stock antigo (anos 60-80) reabilitavel. Liquidez alta em revenda.',
      drivers: ['Praia da Madalena', 'AL/turismo costeiro', 'Estrada Costeira', 'Comboios suburbanos (Linha do Norte)'],
      target_imovel: 'T1/T2 antigos em segunda linha de praia para reabilitacao com saida em AL. Stock pre-1980 com bom preco entrada.',
    },
    {
      nome: 'Santa Marinha e Sao Pedro da Afurada',
      tipologia: 'Urbana premium',
      populacao: 34032,
      area_km2: 6.91,
      preco_eur_m2: 3500,
      preco_range: '2 800 - 5 500',
      var_yoy_pct: 3.0,
      tempo_venda_dias: 55,
      ticket_tipico_t2: '210 000 - 330 000',
      score: 6.5,
      criterios: { preco_entrada: 4, procura_liquidez: 10, servicos_amenidades: 10, potencial_revalorizacao: 7, concorrencia: 3 },
      classificacao: 'monitorizar',
      perfil: 'Ribeira de Gaia, caves de vinho do Porto e Afurada. Zona mais valorizada do concelho. Liquidez excepcional em revenda mas ticket entrada muito acima do target wholesale 100-200k. Util como benchmark e para operacoes pontuais de upside.',
      drivers: ['Caves Vinho do Porto', 'Marginal e ribeira', 'Linha Rubi (Arrabida, Candal)', 'WoW - World of Wine', 'Teleferico'],
      target_imovel: 'Apenas oportunidades pontuais: T0/T1 antigos para reabilitacao com forte upside AL. Operacoes acima do target standard.',
    },
    {
      nome: 'Sao Felix da Marinha',
      tipologia: 'Costeira sul',
      populacao: 13560,
      area_km2: 7.93,
      preco_eur_m2: 2400,
      preco_range: '1 900 - 2 950',
      var_yoy_pct: 4.0,
      tempo_venda_dias: 80,
      ticket_tipico_t2: '145 000 - 210 000',
      score: 6.5,
      criterios: { preco_entrada: 7, procura_liquidez: 7, servicos_amenidades: 6, potencial_revalorizacao: 7, concorrencia: 6 },
      classificacao: 'monitorizar',
      perfil: 'Faixa costeira sul, mais acessivel que Canidelo/Arcozelo. Mistura familias permanentes e segunda habitacao. Stock variado (anos 70 ate construcao recente).',
      drivers: ['Praia de Sao Felix', 'Comboio Linha do Norte (estacao SF Marinha)', 'Acesso A29'],
      target_imovel: 'T2 anos 80-90 para reabilitacao e revenda costeira. T1 para AL sazonal.',
    },
    {
      nome: 'Gulpilhares e Valadares',
      tipologia: 'Costeira premium',
      populacao: 22322,
      area_km2: 10.61,
      preco_eur_m2: 3000,
      preco_range: '2 400 - 4 000',
      var_yoy_pct: 3.0,
      tempo_venda_dias: 70,
      ticket_tipico_t2: '180 000 - 280 000',
      score: 5.8,
      criterios: { preco_entrada: 5, procura_liquidez: 8, servicos_amenidades: 8, potencial_revalorizacao: 6, concorrencia: 4 },
      classificacao: 'evitar',
      perfil: 'Faixa costeira premium com Marina, Praia da Granja e novos empreendimentos. Preco acima do target wholesale. Liquidez alta mas margem comprimida.',
      drivers: ['Marina de Gaia', 'Praia da Granja', 'Linha do Norte', 'A29'],
      target_imovel: 'Fora do target standard. Apenas operacoes premium oportunistas.',
    },
    {
      nome: 'Arcozelo',
      tipologia: 'Costeira sul',
      populacao: 15144,
      area_km2: 8.50,
      preco_eur_m2: 2800,
      preco_range: '2 200 - 3 500',
      var_yoy_pct: 3.0,
      tempo_venda_dias: 80,
      ticket_tipico_t2: '170 000 - 245 000',
      score: 5.5,
      criterios: { preco_entrada: 5, procura_liquidez: 7, servicos_amenidades: 6, potencial_revalorizacao: 6, concorrencia: 5 },
      classificacao: 'evitar',
      perfil: 'Zona costeira sul, residencial. Preco acima do target. Stock recente domina, baixa oportunidade wholesale.',
      drivers: ['Praias Arcozelo/Granja', 'A29'],
      target_imovel: 'Fora do target standard.',
    },
    {
      nome: 'Canidelo',
      tipologia: 'Costeira premium',
      populacao: 28054,
      area_km2: 8.93,
      preco_eur_m2: 3600,
      preco_range: '2 800 - 5 000',
      var_yoy_pct: 5.5,
      tempo_venda_dias: 50,
      ticket_tipico_t2: '220 000 - 340 000',
      score: 5.0,
      criterios: { preco_entrada: 3, procura_liquidez: 10, servicos_amenidades: 9, potencial_revalorizacao: 8, concorrencia: 2 },
      classificacao: 'evitar',
      perfil: 'Zona costeira premium com pipeline de nova construcao (36% do total de Gaia). Preco entrada muito acima do target wholesale. Mercado dominado por promotores nacionais e estrangeiros.',
      drivers: ['Praia de Lavadores e Canidelo', 'Pipeline nova construcao 36% concelho', 'Marginal'],
      target_imovel: 'Fora do target standard.',
    },
    {
      nome: 'Sandim, Olival, Lever e Crestuma',
      tipologia: 'Rural sul',
      populacao: 15956,
      area_km2: 34.16,
      preco_eur_m2: 1400,
      preco_range: '1 100 - 1 700',
      var_yoy_pct: 2.0,
      tempo_venda_dias: 145,
      ticket_tipico_t2: '80 000 - 125 000',
      score: 5.0,
      criterios: { preco_entrada: 10, procura_liquidez: 3, servicos_amenidades: 4, potencial_revalorizacao: 5, concorrencia: 9 },
      classificacao: 'evitar',
      perfil: 'Zona rural e dispersa no extremo sul do concelho. Preco entrada muito baixo mas liquidez fraca. Procura sazonal e restrita a residentes locais. Risco de tempo de venda muito elevado.',
      drivers: ['Pisao do Lever', 'Barragem Crestuma-Lever', 'Acesso A1 distante'],
      target_imovel: 'Apenas oportunidades pontuais: moradias rurais com terreno para mercado de nicho.',
    },
  ],

  drivers_transversais: [
    {
      categoria: 'Transportes — Metro',
      items: [
        'Linha Amarela (D) — Santo Ovidio, terminal em Mafamude (operacional)',
        'Linha Rubi (H) — 6 estacoes em Gaia (Arrabida, Candal, Rotunda, Devesas, Soares dos Reis, Santo Ovidio), conclusao prevista para 2028',
        'Ponte Ferreirinha (futura) — ligacao directa metro Porto-Gaia',
        'Vila d Este — futuro PMO da Linha Rubi (centro de manutencao)',
      ],
    },
    {
      categoria: 'Transportes — Rodoviario e BRT',
      items: [
        'Metrobus Boavista-Praca do Imperio (3.8 km, operacao iniciada 2025)',
        'A1, A29, A44, A20 — eixos estruturantes',
        'Pontes do Freixo, Arrabida, Luiz I e D. Maria — ligacao ao Porto',
      ],
    },
    {
      categoria: 'Saude',
      items: [
        'Hospital Santos Silva (publico, Mafamude)',
        'Hospital da Luz Arrabida (privado, Mafamude)',
        'Hospital Lusiadas Porto (acessivel pela ponte)',
        'Centros de saude por freguesia',
      ],
    },
    {
      categoria: 'Comercio e Servicos',
      items: [
        'Arrabida Shopping (Mafamude, +160 lojas)',
        'Gaia Shopping (Mafamude/Vilar do Paraiso)',
        'El Corte Ingles Gaia (Santa Marinha)',
        'Mercado de Vilar de Andorinho',
        'Mercado Beira-Rio (Santa Marinha)',
      ],
    },
    {
      categoria: 'Educacao',
      items: [
        'Escola Secundaria Almeida Garrett (Mafamude)',
        'Escola Secundaria Ines de Castro (Canelas)',
        'Escola Secundaria Diogo de Macedo (Olival)',
        'Universidade Catolica Polo Foz (acessivel pelo metro)',
      ],
    },
    {
      categoria: 'Cultura e Lazer',
      items: [
        'WoW - World of Wine (Santa Marinha)',
        'Caves do Vinho do Porto',
        'Teleferico de Gaia',
        'Marina de Gaia',
        '+11 praias atlanticas (Madalena, Canidelo, Lavadores, Sao Felix, Granja, Valadares)',
      ],
    },
  ],

  riscos: [
    {
      titulo: 'Pressao fiscal sobre Alojamento Local',
      descricao: 'Mais Habitacao (Lei 56/2023) e normas municipais limitam novos AL em zonas saturadas. Avaliar zona por zona antes de comprometer exit em AL.',
      mitigacao: 'Confirmar zonas elegiveis na CM Gaia antes da aquisicao. Privilegiar saida em revenda ou arrendamento de longa duracao.',
    },
    {
      titulo: 'Concorrencia agressiva de promotores nacionais',
      descricao: 'Canidelo, Mafamude e Santa Marinha concentram 77% do pipeline 2024-2025. Risco de saturacao em segmento medio-alto.',
      mitigacao: 'Focar em stock antigo (pre-1990) para reabilitacao. Evitar competir com nova construcao.',
    },
    {
      titulo: 'Atraso da Linha Rubi (2026 -> 2028)',
      descricao: 'O upside de valorizacao das estacoes do metro adia-se. Plano financeiro nao pode contar com efeito metro como driver de exit antes de 2028.',
      mitigacao: 'Modelar exits sem premio de metro. Tratar valorizacao como upside opcional.',
    },
    {
      titulo: 'Dependencia do Porto e do turismo',
      descricao: 'Procura em Gaia tem correlacao alta com fluxo turistico Porto + AL. Crise turistica poderia comprometer exits em zonas costeiras.',
      mitigacao: 'Diversificar carteira entre zonas urbanas (procura residencial estavel) e zonas costeiras (procura sazonal).',
    },
    {
      titulo: 'Sazonalidade do mercado costeiro',
      descricao: 'Madalena, Canidelo, Sao Felix e Arcozelo concentram transaccoes em primavera/verao. Tempo de venda fora desta janela pode duplicar.',
      mitigacao: 'Timing de aquisicao Q4-Q1 e exit Q2-Q3.',
    },
    {
      titulo: 'Custos de obra e disponibilidade de empreiteiro',
      descricao: 'Empreiteiro identificado para Gaia mas capacidade de execucao tem que escalar conforme volume de captacoes.',
      mitigacao: 'Manter 2-3 empreiteiros parceiros em pipeline. Confirmar orcamentos antes de fechar com investidor.',
    },
  ],

  proximos_passos: [
    { fase: 'Dias 0-30', accoes: [
      'Recrutar 2-3 consultores imobiliarios locais (zonas Mafamude, Oliveira do Douro, Vilar de Andorinho)',
      'Visitar empreiteiro e validar capacidade para 5-8 obras em paralelo',
      'Abrir contas no Idealista Pro e Imovirtual Pro para angariacao directa',
      'Listar 50 leads ativos nas 5 zonas Top 5 (banco, mediadores, particulares)',
    ]},
    { fase: 'Dias 31-60', accoes: [
      'Fechar primeiras 2-3 captacoes piloto (uma em Mafamude, uma em Oliveira do Douro, uma em Vilar de Andorinho)',
      'Validar orcamentos detalhados com empreiteiro para cada operacao',
      'Apresentar a investidores CAEP com dossier por imovel + dossier macro Gaia',
      'Confirmar pipeline de 10+ leads adicionais qualificados',
    ]},
    { fase: 'Dias 61-90', accoes: [
      'Fechar primeiras 2 cedencias de posicao em Gaia',
      'Iniciar obras nas 3 captacoes piloto',
      'Avaliar metricas: tempo de captacao, margem media, NPS investidor',
      'Decisao Go/No-Go para escalar ou ajustar mix de zonas',
    ]},
  ],

  fontes: [
    { nome: 'Observatorio Imobiliario de Gaia (Camara Municipal + Confidencial Imobiliario)', url: 'https://obigaia.pt/pt/', data: '2026-05-26' },
    { nome: 'INE — Censos 2021 (populacao por freguesia)', url: 'https://censos.ine.pt/', data: '2021 (publicado 2022-2023)' },
    { nome: 'Idealista — Evolucao preco habitacao Vila Nova de Gaia', url: 'https://www.idealista.pt/media/relatorios-preco-habitacao/venda/porto/vila-nova-de-gaia/', data: '2026-01' },
    { nome: 'Camara Municipal de Gaia — Comunicado de imprensa Habitacao 2024', url: 'https://www.cm-gaia.pt/pt/noticias/gaia-afirma-se-como-principal-destino-para-o-investimento-em-nova-habitacao/', data: '2025' },
    { nome: 'Linha Rubi — Metro do Porto (informacao oficial)', url: 'https://linharubi.metrodoporto.pt/', data: '2026-04' },
    { nome: 'Best Yield Finder — Vila Nova de Gaia Real Estate Market', url: 'https://www.bestyieldfinder.com/en/portugal/vila-nova-de-gaia', data: '2026-05-03' },
    { nome: 'Casa SAPO — Listagens Vila Nova de Gaia (snapshot)', url: 'https://casa.sapo.pt/', data: '2026-05-26' },
    { nome: 'SuperCasa — Listagens Vila Nova de Gaia (snapshot)', url: 'https://supercasa.pt/', data: '2026-05-26' },
    { nome: 'Jornal Economico — Habitacao Vila Nova de Gaia licencia ao dobro do ritmo do pais', url: 'https://jornaleconomico.sapo.pt/noticias/habitacao-vila-nova-de-gaia-licencia-ao-dobro-do-ritmo-do-pais/', data: '2025' },
  ],
}

export default DADOS_EXPANSAO_GAIA
